### PR TITLE
More python porting ...

### PR DESCRIPTION
**Pull request by SSoulaimane**
This is as far as I can go for now. Perhaps you can continue the porting.

### CODE REVIEW

**Comment by Metallicow** [comment]
@SSoulaimane Ummm... Exactly what is the licensing on this pull REQz? I noticed GPLish license added. Would you please explain the intentions and or correct them as to what it applies too.

The original intent was zlib licensing as a whole for the library and application, and I wholeheartedly will follow that until the 1st stable RELz. So as far as your contributions if only the docs part is GPL... related please remove that or find another way to make it free'er. 

I myself lived on the streets homeless for 2 years, finally finding myself a decent job because of the work I had done for it and by word of mouth. I wouldn't want any less effort from those that wish to see this project succeed for all; not for me. We create jobs. True freedom is at stake here. To this date I have helped this project succeed and have not made a dollar one and we are the best open source solution out there. So therefore I wish and probably know a bit better than most that the code licensing is at this point unquestionable for the freedom of all. I myself do not specialize in CNC, but do 3D if you might say that. By providing the free-ist(?) license allows everybody to do what they want from the point of officially becoming the "official" resource. Credits is always honored.

Who knows... maybe you will be the first one collecting benefits from this or obtain a DEV position with us. I can see you have spent the time to familiarize yourself with the code(4+ hr reviewing myself), and that is highly appreciated... There just needs to be some more clarification before code is merged. Is the doc or code output GPL'd(That includes the code, which probably would be unlikely to make upstream at this point in time)?

Please and thanks, mooo,
 -Metalio Bovinus, embPython DEV

**Comment by SSoulaimane** [comment]
yes it is the hacked up docgen package only that is licensed as LGPL, but no problem I'm changing the license to zlib

**Comment by Metallicow** [comment]
@SSoulaimane 
Thanks.
What is your developer handle/credit? Please do that in a commit yourself. You will not be forgotten.

**Comment by SSoulaimane** [comment]
it's already in there in the file `.../hacks/docgen/__init__.py`

**Comment by Metallicow** [comment]
OK. Thanks my brothers/sisters. Stitchify!
Merged.

**Pull request merged**
